version: "3"

volumes:
  database:
    driver: local

services:
  postgres:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: raghav
      POSTGRES_PASSWORD: password
      POSTGRES_DB: chatbot
    ports:
      - "5432:5432"
    volumes:
      - /home/raghav/code/JS/postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: node_app
  #   depends_on:
  #     - postgres
  #   environment:
  #     NODE_ENV: development
  #   env_file:
  #     - .env
  #   ports:
  #     - "3000:3000"
  #     - "8080:8080"
  #   volumes:
  #     - .:/app
  #     - /app/node_modules
  #   networks:
  #     - app-network

networks:
  app-network:
    driver: bridge